version: "3.3"
services:

  mssql-2017:
    image: microsoft/mssql-server-linux:2017-latest
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - ./Sqldata:/var/opt/mssql
      - ./usecontaineddbauth.sql:/var/opt/usecontaineddbauth.sql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Qwerty123

  solr-6-6-2-ssl:
    image: solr:6.6.2
    restart: always
    ports:
      - 8983:8983
    environment:
      - SOLR_SSL_KEY_STORE=/opt/solr/server/certs/solr-ssl.keystore.pfx
      - SOLR_SSL_TRUST_STORE=/opt/solr/server/certs/solr-ssl.keystore.pfx
      - SOLR_SSL_KEY_STORE_PASSWORD=123SecureSolr!
      - SOLR_SSL_TRUST_STORE_PASSWORD=123SecureSolr!
    volumes:
      - ./certs:/opt/solr/server/certs
      - ./solr_home/solr/server/solr:/opt/solr/server/solr
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    tty: true  